git(pre-commit): fix project specific exit non-zero

diff --git a/gitconfig/hooks/executable_pre-commit b/gitconfig/hooks/executable_pre-commit
--- a/gitconfig/hooks/executable_pre-commit
+++ b/gitconfig/hooks/executable_pre-commit
@@ -6,6 +6,9 @@
 # You can use bash if you prefere it over zsh, and ag
 # over rg.
 
+# Exit if subcommand return non-zero
+set -e
+
 # Execute project pre-commit hook if exist
 if [ -x ".git/hooks/pre-commit" ]; then
   echo "Executing project-specific pre-commit hook..."
